echo "1024-bfs-lru1" >> result.txt; cat gem5/1024-bfs-lru1/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "1024-bfs-lru2" >> result.txt; cat gem5/1024-bfs-lru2/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "1024-bfs-ship1" >> result.txt; cat gem5/1024-bfs-ship1/stats.txt| grep system.l2.overall_miss_rate >> result.txt   
echo "1024-bfs-ship2" >> result.txt; cat gem5/1024-bfs-ship2/stats.txt| grep system.l2.overall_miss_rate >> result.txt   
echo "1024-bfs-srrip1" >> result.txt; cat gem5/1024-bfs-srrip1/stats.txt| grep system.l2.overall_miss_rate >> result.txt  
echo "1024-bfs-srrip2" >> result.txt; cat gem5/1024-bfs-srrip2/stats.txt| grep system.l2.overall_miss_rate >> result.txt  
echo "1024-mst-lru1" >> result.txt; cat gem5/1024-mst-lru1/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "1024-mst-lru2" >> result.txt; cat gem5/1024-mst-lru2/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "1024-mst-ship1" >> result.txt; cat gem5/1024-mst-ship1/stats.txt| grep system.l2.overall_miss_rate >> result.txt   
echo "1024-mst-ship2" >> result.txt; cat gem5/1024-mst-ship2/stats.txt| grep system.l2.overall_miss_rate >> result.txt
echo "1024-mst-srrip1" >> result.txt; cat gem5/1024-mst-srrip1/stats.txt| grep system.l2.overall_miss_rate >> result.txt
echo "1024-mst-srrip2" >> result.txt; cat gem5/1024-mst-srrip2/stats.txt| grep system.l2.overall_miss_rate >> result.txt
echo "256-bfs-lru1" >> result.txt; cat gem5/256-bfs-lru1/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "256-bfs-lru2" >> result.txt; cat gem5/256-bfs-lru2/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "256-bfs-ship1" >> result.txt; cat gem5/256-bfs-ship1/stats.txt| grep system.l2.overall_miss_rate >> result.txt   
echo "256-bfs-ship2" >> result.txt; cat gem5/256-bfs-ship2/stats.txt| grep system.l2.overall_miss_rate >> result.txt   
echo "256-bfs-srrip1" >> result.txt; cat gem5/256-bfs-srrip1/stats.txt| grep system.l2.overall_miss_rate >> result.txt  
echo "256-bfs-srrip2" >> result.txt; cat gem5/256-bfs-srrip2/stats.txt| grep system.l2.overall_miss_rate >> result.txt  
echo "256-mst-lru1" >> result.txt; cat gem5/256-mst-lru1/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "256-mst-lru2" >> result.txt; cat gem5/256-mst-lru2/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "256-mst-ship1" >> result.txt; cat gem5/256-mst-ship1/stats.txt| grep system.l2.overall_miss_rate >> result.txt   
echo "256-mst-ship2" >> result.txt; cat gem5/256-mst-ship2/stats.txt| grep system.l2.overall_miss_rate >> result.txt
echo "256-mst-srrip1" >> result.txt; cat gem5/256-mst-srrip1/stats.txt| grep system.l2.overall_miss_rate >> result.txt
echo "256-mst-srrip2" >> result.txt; cat gem5/256-mst-srrip2/stats.txt| grep system.l2.overall_miss_rate >> result.txt
echo "4096-bfs-lru1" >> result.txt; cat gem5/4096-bfs-lru1/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "4096-bfs-lru2" >> result.txt; cat gem5/4096-bfs-lru2/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "4096-bfs-ship1" >> result.txt; cat gem5/4096-bfs-ship1/stats.txt| grep system.l2.overall_miss_rate >> result.txt   
echo "4096-bfs-ship2" >> result.txt; cat gem5/4096-bfs-ship2/stats.txt| grep system.l2.overall_miss_rate >> result.txt   
echo "4096-bfs-srrip1" >> result.txt; cat gem5/4096-bfs-srrip1/stats.txt| grep system.l2.overall_miss_rate >> result.txt  
echo "4096-bfs-srrip2" >> result.txt; cat gem5/4096-bfs-srrip2/stats.txt| grep system.l2.overall_miss_rate >> result.txt  
echo "4096-mst-lru1" >> result.txt; cat gem5/4096-mst-lru1/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "4096-mst-lru2" >> result.txt; cat gem5/4096-mst-lru2/stats.txt| grep system.l2.overall_miss_rate >> result.txt    
echo "4096-mst-ship1" >> result.txt; cat gem5/4096-mst-ship1/stats.txt| grep system.l2.overall_miss_rate >> result.txt   
echo "4096-mst-ship2" >> result.txt; cat gem5/4096-mst-ship2/stats.txt| grep system.l2.overall_miss_rate >> result.txt
echo "4096-mst-srrip1" >> result.txt; cat gem5/4096-mst-srrip1/stats.txt| grep system.l2.overall_miss_rate >> result.txt
echo "4096-mst-srrip2" >> result.txt; cat gem5/4096-mst-srrip2/stats.txt| grep system.l2.overall_miss_rate >> result.txt